//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RegistrationProcess.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    using RegistrationProcess.Models.Constants;

    public partial class ProductInformation
    {
        public long EbProductId { get; set; }

        [Required(ErrorMessageResourceName = "ProductNameRequiredMsg",ErrorMessageResourceType =typeof(LocalizedErrorMsg), AllowEmptyStrings = false)]
        [StringLength(50)]
        public string Name { get; set; }

        [Required(ErrorMessageResourceName = "ProductEndPointRequiredMsg",ErrorMessageResourceType =typeof(LocalizedErrorMsg), AllowEmptyStrings = false)]
        public string EndpointURL { get; set; }

        [Required(ErrorMessageResourceName = "ProductSecretRequiredMsg", ErrorMessageResourceType =typeof(LocalizedErrorMsg), AllowEmptyStrings = false)]
        public string ProductSecret { get; set; }

        [EmailAddress(ErrorMessageResourceName = "EmailNotValidMsg", ErrorMessageResourceType =typeof(LocalizedErrorMsg))]
        public string EmailId { get; set; }

        [Phone]
        public string Phone { get; set; }

        public string Website { get; set; }
        public string IPAddress { get; set; }
        public string ServiceOffered { get; set; }
        public string ProductStatus { get; set; }
    }
}
