/*
 * Education Brands Integration Service APIs
 *
 * The integration framework is an attempt to define a standard and simple socket each brand can plug in to interact with other EB products. It defines what each product needs to do to integrate with other products. It has a set of API to interact with other products and what each product should implement to receive communication from other products. This is an API specification detailing the APIs for Education Brands IntegrationService.  Most of these APIs will be implemented in EBIS.  The APIs in the 'Product Endpoints' section has to be implemented by each of the Products.  <b>NOTE - <i>This specification is still in early development stage and is subject to change without notice.</i></b> 
 *
 * OpenAPI spec version: 1.0.0
 * Contact: sobin@schoolspeak.com
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *      http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

using CB.IntegrationService.ApiModels;
using System;
using System.Web.Http;

namespace EducationBrands.IntegrationService.Api.Controllers
{
    /// <summary>
    /// 
    /// </summary>
    public class InstitutionController : ApiController
    { 
        /// <summary>
        /// Disable Integration for product
        /// </summary>
        /// <remarks>API for an institution to disable integration for its product</remarks>
        /// <param name="ebInstitutionId">The Education brands institution id</param>
        /// <param name="ebProductId">The Education brands product id</param>
        /// <response code="200">Successfully disabled integration for the product</response>
        [HttpDelete]
        [Route("EducationBrands/EBIS/1.0.0/institutions/{ebInstitutionId}/products/{ebProductId}")]
        public virtual void DisableProductInstitutionIntegration(string ebInstitutionId, string ebProductId)
        { 
            throw new NotImplementedException();
        }

        /// <summary>
        /// Get Services
        /// </summary>
        /// <remarks>Gets a list of all services offered by different products for the specified institution</remarks>
        /// <param name="ebInstitutionId">The Education brands institution id</param>
        /// <response code="200">Successfully returned the services used by the institution</response>
        [HttpGet]
        [Route("EducationBrands/EBIS/1.0.0/institutions/{ebInstitutionId}/products")]
        public virtual IHttpActionResult GetServicesRequest(string ebInstitutionId)
        {
            return BadRequest("This method has not been implemented");
        }

        /// <summary>
        /// Register a new Institution for Integration
        /// </summary>
        /// <remarks>Registeres a new institution for Integration. THis must be done before using the services of EBIS.</remarks>
        /// <param name="registerInstitutionRequest"></param>
        /// <response code="200">Institution registered successfully with EBIS</response>
        /// <response code="409">Conflict. The institution has already been registered for integration</response>
        [HttpPost]
        [Route("EducationBrands/EBIS/1.0.0/institutions")]
        public virtual IHttpActionResult RegisterInstitution([FromBody]RegisterInstitutionRequest registerInstitutionRequest)
        {
            return BadRequest("This method has not been implemented");
        }
    }
}
