/* 
 * Education Brands Integration Service APIs
 *
 * The integration framework is an attempt to define a standard and simple socket each brand can plug in to interact with other EB products. It defines what each product needs to do to integrate with other products. It has a set of API to interact with other products and what each product should implement to receive communication from other products. This is an API specification detailing the APIs for Education Brands IntegrationService.  Most of these APIs will be implemented in EBIS.  The APIs in the 'Product Endpoints' section has to be implemented by each of the Products.  <b>NOTE - <i>This specification is still in early development stage and is subject to change without notice.</i></b> 
 *
 * OpenAPI spec version: 1.0.0
 * Contact: sobin@schoolspeak.com
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */

using Newtonsoft.Json;
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Runtime.Serialization;
using System.Text;

namespace CB.IntegrationService.ApiModels
{
    /// <summary>
    /// ErrorNotificationRequest
    /// </summary>
    [DataContract]
    public partial class ErrorNotificationRequest :  IEquatable<ErrorNotificationRequest>, IValidatableObject
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="ErrorNotificationRequest" /> class.
        /// </summary>
        /// <param name="ProductID">EBID of the product.</param>
        /// <param name="ProductName">Name of the product.</param>
        /// <param name="RequestTimestamp">Request processed time stamp in UTC.</param>
        /// <param name="RequestId">unique Id for a request.</param>
        /// <param name="StatusCode">The status code.</param>
        /// <param name="StatusMessage">Array of error messages.</param>
        public ErrorNotificationRequest(string ProductID = default(string), string ProductName = default(string), string RequestTimestamp = default(string), string RequestId = default(string), string StatusCode = default(string), List<string> StatusMessage = default(List<string>))
        {
            this.ProductID = ProductID;
            this.ProductName = ProductName;
            this.RequestTimestamp = RequestTimestamp;
            this.RequestId = RequestId;
            this.StatusCode = StatusCode;
            this.StatusMessage = StatusMessage;
        }
        
        /// <summary>
        /// EBID of the product
        /// </summary>
        /// <value>EBID of the product</value>
        [DataMember(Name="productID", EmitDefaultValue=false)]
        public string ProductID { get; set; }

        /// <summary>
        /// Name of the product
        /// </summary>
        /// <value>Name of the product</value>
        [DataMember(Name="productName", EmitDefaultValue=false)]
        public string ProductName { get; set; }

        /// <summary>
        /// Request processed time stamp in UTC
        /// </summary>
        /// <value>Request processed time stamp in UTC</value>
        [DataMember(Name="RequestTimestamp", EmitDefaultValue=false)]
        public string RequestTimestamp { get; set; }

        /// <summary>
        /// unique Id for a request
        /// </summary>
        /// <value>unique Id for a request</value>
        [DataMember(Name="RequestId", EmitDefaultValue=false)]
        public string RequestId { get; set; }

        /// <summary>
        /// The status code
        /// </summary>
        /// <value>The status code</value>
        [DataMember(Name="StatusCode", EmitDefaultValue=false)]
        public string StatusCode { get; set; }

        /// <summary>
        /// Array of error messages
        /// </summary>
        /// <value>Array of error messages</value>
        [DataMember(Name="StatusMessage", EmitDefaultValue=false)]
        public List<string> StatusMessage { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            var sb = new StringBuilder();
            sb.Append("class ErrorNotificationRequest {\n");
            sb.Append("  ProductID: ").Append(ProductID).Append("\n");
            sb.Append("  ProductName: ").Append(ProductName).Append("\n");
            sb.Append("  RequestTimestamp: ").Append(RequestTimestamp).Append("\n");
            sb.Append("  RequestId: ").Append(RequestId).Append("\n");
            sb.Append("  StatusCode: ").Append(StatusCode).Append("\n");
            sb.Append("  StatusMessage: ").Append(StatusMessage).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }
  
        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public string ToJson()
        {
            return JsonConvert.SerializeObject(this, Formatting.Indented);
        }

        /// <summary>
        /// Returns true if objects are equal
        /// </summary>
        /// <param name="input">Object to be compared</param>
        /// <returns>Boolean</returns>
        public override bool Equals(object input)
        {
            return this.Equals(input as ErrorNotificationRequest);
        }

        /// <summary>
        /// Returns true if ErrorNotificationRequest instances are equal
        /// </summary>
        /// <param name="input">Instance of ErrorNotificationRequest to be compared</param>
        /// <returns>Boolean</returns>
        public bool Equals(ErrorNotificationRequest input)
        {
            if (input == null)
                return false;

            return 
                (
                    this.ProductID == input.ProductID ||
                    (this.ProductID != null &&
                    this.ProductID.Equals(input.ProductID))
                ) && 
                (
                    this.ProductName == input.ProductName ||
                    (this.ProductName != null &&
                    this.ProductName.Equals(input.ProductName))
                ) && 
                (
                    this.RequestTimestamp == input.RequestTimestamp ||
                    (this.RequestTimestamp != null &&
                    this.RequestTimestamp.Equals(input.RequestTimestamp))
                ) && 
                (
                    this.RequestId == input.RequestId ||
                    (this.RequestId != null &&
                    this.RequestId.Equals(input.RequestId))
                ) && 
                (
                    this.StatusCode == input.StatusCode ||
                    (this.StatusCode != null &&
                    this.StatusCode.Equals(input.StatusCode))
                ) && 
                (
                    this.StatusMessage == input.StatusMessage ||
                    this.StatusMessage != null &&
                    this.StatusMessage.SequenceEqual(input.StatusMessage)
                );
        }

        /// <summary>
        /// Gets the hash code
        /// </summary>
        /// <returns>Hash code</returns>
        public override int GetHashCode()
        {
            unchecked // Overflow is fine, just wrap
            {
                int hashCode = 41;
                if (this.ProductID != null)
                    hashCode = hashCode * 59 + this.ProductID.GetHashCode();
                if (this.ProductName != null)
                    hashCode = hashCode * 59 + this.ProductName.GetHashCode();
                if (this.RequestTimestamp != null)
                    hashCode = hashCode * 59 + this.RequestTimestamp.GetHashCode();
                if (this.RequestId != null)
                    hashCode = hashCode * 59 + this.RequestId.GetHashCode();
                if (this.StatusCode != null)
                    hashCode = hashCode * 59 + this.StatusCode.GetHashCode();
                if (this.StatusMessage != null)
                    hashCode = hashCode * 59 + this.StatusMessage.GetHashCode();
                return hashCode;
            }
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        IEnumerable<System.ComponentModel.DataAnnotations.ValidationResult> IValidatableObject.Validate(ValidationContext validationContext)
        {
            yield break;
        }
    }

}
