/* 
 * Education Brands Integration Service APIs
 *
 * The integration framework is an attempt to define a standard and simple socket each brand can plug in to interact with other EB products. It defines what each product needs to do to integrate with other products. It has a set of API to interact with other products and what each product should implement to receive communication from other products. This is an API specification detailing the APIs for Education Brands IntegrationService.  Most of these APIs will be implemented in EBIS.  The APIs in the 'Product Endpoints' section has to be implemented by each of the Products.  <b>NOTE - <i>This specification is still in early development stage and is subject to change without notice.</i></b> 
 *
 * OpenAPI spec version: 1.0.0
 * Contact: sobin@schoolspeak.com
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */

using Newtonsoft.Json;
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Runtime.Serialization;
using System.Text;

namespace CB.IntegrationService.ApiModels
{
    /// <summary>
    /// NotificationAcknowledgeRequest
    /// </summary>
    [DataContract]
    public partial class NotificationAcknowledgeRequest :  IEquatable<NotificationAcknowledgeRequest>, IValidatableObject
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="NotificationAcknowledgeRequest" /> class.
        /// </summary>
        /// <param name="AcknowledgeTimestamp">Acknowledgment time stamp in UTC.</param>
        /// <param name="RequestTimestamp">Request processed time stamp in UTC.</param>
        /// <param name="EventToken">Event token.</param>
        /// <param name="StatusCode">Event token.</param>
        /// <param name="StatusMessage">successfully processed.</param>
        public NotificationAcknowledgeRequest(string AcknowledgeTimestamp = default(string), string RequestTimestamp = default(string), string EventToken = default(string), string StatusCode = default(string), string StatusMessage = default(string))
        {
            this.AcknowledgeTimestamp = AcknowledgeTimestamp;
            this.RequestTimestamp = RequestTimestamp;
            this.EventToken = EventToken;
            this.StatusCode = StatusCode;
            this.StatusMessage = StatusMessage;
        }
        
        /// <summary>
        /// Acknowledgment time stamp in UTC
        /// </summary>
        /// <value>Acknowledgment time stamp in UTC</value>
        [DataMember(Name="AcknowledgeTimestamp", EmitDefaultValue=false)]
        public string AcknowledgeTimestamp { get; set; }

        /// <summary>
        /// Request processed time stamp in UTC
        /// </summary>
        /// <value>Request processed time stamp in UTC</value>
        [DataMember(Name="RequestTimestamp", EmitDefaultValue=false)]
        public string RequestTimestamp { get; set; }

        /// <summary>
        /// Event token
        /// </summary>
        /// <value>Event token</value>
        [DataMember(Name="EventToken", EmitDefaultValue=false)]
        public string EventToken { get; set; }

        /// <summary>
        /// Event token
        /// </summary>
        /// <value>Event token</value>
        [DataMember(Name="StatusCode", EmitDefaultValue=false)]
        public string StatusCode { get; set; }

        /// <summary>
        /// successfully processed
        /// </summary>
        /// <value>successfully processed</value>
        [DataMember(Name="StatusMessage", EmitDefaultValue=false)]
        public string StatusMessage { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            var sb = new StringBuilder();
            sb.Append("class NotificationAcknowledgeRequest {\n");
            sb.Append("  AcknowledgeTimestamp: ").Append(AcknowledgeTimestamp).Append("\n");
            sb.Append("  RequestTimestamp: ").Append(RequestTimestamp).Append("\n");
            sb.Append("  EventToken: ").Append(EventToken).Append("\n");
            sb.Append("  StatusCode: ").Append(StatusCode).Append("\n");
            sb.Append("  StatusMessage: ").Append(StatusMessage).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }
  
        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public string ToJson()
        {
            return JsonConvert.SerializeObject(this, Formatting.Indented);
        }

        /// <summary>
        /// Returns true if objects are equal
        /// </summary>
        /// <param name="input">Object to be compared</param>
        /// <returns>Boolean</returns>
        public override bool Equals(object input)
        {
            return this.Equals(input as NotificationAcknowledgeRequest);
        }

        /// <summary>
        /// Returns true if NotificationAcknowledgeRequest instances are equal
        /// </summary>
        /// <param name="input">Instance of NotificationAcknowledgeRequest to be compared</param>
        /// <returns>Boolean</returns>
        public bool Equals(NotificationAcknowledgeRequest input)
        {
            if (input == null)
                return false;

            return 
                (
                    this.AcknowledgeTimestamp == input.AcknowledgeTimestamp ||
                    (this.AcknowledgeTimestamp != null &&
                    this.AcknowledgeTimestamp.Equals(input.AcknowledgeTimestamp))
                ) && 
                (
                    this.RequestTimestamp == input.RequestTimestamp ||
                    (this.RequestTimestamp != null &&
                    this.RequestTimestamp.Equals(input.RequestTimestamp))
                ) && 
                (
                    this.EventToken == input.EventToken ||
                    (this.EventToken != null &&
                    this.EventToken.Equals(input.EventToken))
                ) && 
                (
                    this.StatusCode == input.StatusCode ||
                    (this.StatusCode != null &&
                    this.StatusCode.Equals(input.StatusCode))
                ) && 
                (
                    this.StatusMessage == input.StatusMessage ||
                    (this.StatusMessage != null &&
                    this.StatusMessage.Equals(input.StatusMessage))
                );
        }

        /// <summary>
        /// Gets the hash code
        /// </summary>
        /// <returns>Hash code</returns>
        public override int GetHashCode()
        {
            unchecked // Overflow is fine, just wrap
            {
                int hashCode = 41;
                if (this.AcknowledgeTimestamp != null)
                    hashCode = hashCode * 59 + this.AcknowledgeTimestamp.GetHashCode();
                if (this.RequestTimestamp != null)
                    hashCode = hashCode * 59 + this.RequestTimestamp.GetHashCode();
                if (this.EventToken != null)
                    hashCode = hashCode * 59 + this.EventToken.GetHashCode();
                if (this.StatusCode != null)
                    hashCode = hashCode * 59 + this.StatusCode.GetHashCode();
                if (this.StatusMessage != null)
                    hashCode = hashCode * 59 + this.StatusMessage.GetHashCode();
                return hashCode;
            }
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        IEnumerable<System.ComponentModel.DataAnnotations.ValidationResult> IValidatableObject.Validate(ValidationContext validationContext)
        {
            yield break;
        }
    }

}
