/* 
 * Education Brands Integration Service APIs
 *
 * The integration framework is an attempt to define a standard and simple socket each brand can plug in to interact with other EB products. It defines what each product needs to do to integrate with other products. It has a set of API to interact with other products and what each product should implement to receive communication from other products. This is an API specification detailing the APIs for Education Brands IntegrationService.  Most of these APIs will be implemented in EBIS.  The APIs in the 'Product Endpoints' section has to be implemented by each of the Products.  <b>NOTE - <i>This specification is still in early development stage and is subject to change without notice.</i></b> 
 *
 * OpenAPI spec version: 1.0.0
 * Contact: sobin@schoolspeak.com
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */

using Newtonsoft.Json;
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Runtime.Serialization;
using System.Text;

namespace CB.IntegrationService.ApiModels
{
    /// <summary>
    /// ProductServices
    /// </summary>
    [DataContract]
    public partial class ProductServices :  IEquatable<ProductServices>, IValidatableObject
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="ProductServices" /> class.
        /// </summary>
        /// <param name="EBProductId">The Education Brands product Id.</param>
        /// <param name="ProductName">The product Name.</param>
        /// <param name="ServicesOffered">A list of services of the product.</param>
        public ProductServices(string EBProductId = default(string), string ProductName = default(string), List<string> ServicesOffered = default(List<string>))
        {
            this.EBProductId = EBProductId;
            this.ProductName = ProductName;
            this.ServicesOffered = ServicesOffered;
        }
        
        /// <summary>
        /// The Education Brands product Id
        /// </summary>
        /// <value>The Education Brands product Id</value>
        [DataMember(Name="EBProductId", EmitDefaultValue=false)]
        public string EBProductId { get; set; }

        /// <summary>
        /// The product Name
        /// </summary>
        /// <value>The product Name</value>
        [DataMember(Name="ProductName", EmitDefaultValue=false)]
        public string ProductName { get; set; }

        /// <summary>
        /// A list of services of the product
        /// </summary>
        /// <value>A list of services of the product</value>
        [DataMember(Name="servicesOffered", EmitDefaultValue=false)]
        public List<string> ServicesOffered { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            var sb = new StringBuilder();
            sb.Append("class ProductServices {\n");
            sb.Append("  EBProductId: ").Append(EBProductId).Append("\n");
            sb.Append("  ProductName: ").Append(ProductName).Append("\n");
            sb.Append("  ServicesOffered: ").Append(ServicesOffered).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }
  
        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public string ToJson()
        {
            return JsonConvert.SerializeObject(this, Formatting.Indented);
        }

        /// <summary>
        /// Returns true if objects are equal
        /// </summary>
        /// <param name="input">Object to be compared</param>
        /// <returns>Boolean</returns>
        public override bool Equals(object input)
        {
            return this.Equals(input as ProductServices);
        }

        /// <summary>
        /// Returns true if ProductServices instances are equal
        /// </summary>
        /// <param name="input">Instance of ProductServices to be compared</param>
        /// <returns>Boolean</returns>
        public bool Equals(ProductServices input)
        {
            if (input == null)
                return false;

            return 
                (
                    this.EBProductId == input.EBProductId ||
                    (this.EBProductId != null &&
                    this.EBProductId.Equals(input.EBProductId))
                ) && 
                (
                    this.ProductName == input.ProductName ||
                    (this.ProductName != null &&
                    this.ProductName.Equals(input.ProductName))
                ) && 
                (
                    this.ServicesOffered == input.ServicesOffered ||
                    this.ServicesOffered != null &&
                    this.ServicesOffered.SequenceEqual(input.ServicesOffered)
                );
        }

        /// <summary>
        /// Gets the hash code
        /// </summary>
        /// <returns>Hash code</returns>
        public override int GetHashCode()
        {
            unchecked // Overflow is fine, just wrap
            {
                int hashCode = 41;
                if (this.EBProductId != null)
                    hashCode = hashCode * 59 + this.EBProductId.GetHashCode();
                if (this.ProductName != null)
                    hashCode = hashCode * 59 + this.ProductName.GetHashCode();
                if (this.ServicesOffered != null)
                    hashCode = hashCode * 59 + this.ServicesOffered.GetHashCode();
                return hashCode;
            }
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        IEnumerable<System.ComponentModel.DataAnnotations.ValidationResult> IValidatableObject.Validate(ValidationContext validationContext)
        {
            yield break;
        }
    }

}
