/* 
 * Education Brands Integration Service APIs
 *
 * The integration framework is an attempt to define a standard and simple socket each brand can plug in to interact with other EB products. It defines what each product needs to do to integrate with other products. It has a set of API to interact with other products and what each product should implement to receive communication from other products. This is an API specification detailing the APIs for Education Brands IntegrationService.  Most of these APIs will be implemented in EBIS.  The APIs in the 'Product Endpoints' section has to be implemented by each of the Products.  <b>NOTE - <i>This specification is still in early development stage and is subject to change without notice.</i></b> 
 *
 * OpenAPI spec version: 1.0.0
 * Contact: sobin@schoolspeak.com
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */

using Newtonsoft.Json;
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Runtime.Serialization;
using System.Text;

namespace CB.IntegrationService.ApiModels
{
    /// <summary>
    /// QueryPayload
    /// </summary>
    [DataContract]
    public partial class QueryPayload :  IEquatable<QueryPayload>, IValidatableObject
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="QueryPayload" /> class.
        /// </summary>
        /// <param name="EBIntegrationUserId">Education Brands User Id.</param>
        /// <param name="FirstName">User First Name.</param>
        /// <param name="LastName">User Last Name.</param>
        /// <param name="Gender">User Gender.</param>
        /// <param name="Admission">Admission.</param>
        public QueryPayload(string EBIntegrationUserId = default(string), string FirstName = default(string), string LastName = default(string), string Gender = default(string), List<QueryInformation> Admission = default(List<QueryInformation>))
        {
            this.EBIntegrationUserId = EBIntegrationUserId;
            this.FirstName = FirstName;
            this.LastName = LastName;
            this.Gender = Gender;
            this.Admission = Admission;
        }
        
        /// <summary>
        /// Education Brands User Id
        /// </summary>
        /// <value>Education Brands User Id</value>
        [DataMember(Name="EBIntegrationUserId", EmitDefaultValue=false)]
        public string EBIntegrationUserId { get; set; }

        /// <summary>
        /// User First Name
        /// </summary>
        /// <value>User First Name</value>
        [DataMember(Name="FirstName", EmitDefaultValue=false)]
        public string FirstName { get; set; }

        /// <summary>
        /// User Last Name
        /// </summary>
        /// <value>User Last Name</value>
        [DataMember(Name="LastName", EmitDefaultValue=false)]
        public string LastName { get; set; }

        /// <summary>
        /// User Gender
        /// </summary>
        /// <value>User Gender</value>
        [DataMember(Name="Gender", EmitDefaultValue=false)]
        public string Gender { get; set; }

        /// <summary>
        /// Gets or Sets Admission
        /// </summary>
        [DataMember(Name="Admission", EmitDefaultValue=false)]
        public List<QueryInformation> Admission { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            var sb = new StringBuilder();
            sb.Append("class QueryPayload {\n");
            sb.Append("  EBIntegrationUserId: ").Append(EBIntegrationUserId).Append("\n");
            sb.Append("  FirstName: ").Append(FirstName).Append("\n");
            sb.Append("  LastName: ").Append(LastName).Append("\n");
            sb.Append("  Gender: ").Append(Gender).Append("\n");
            sb.Append("  Admission: ").Append(Admission).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }
  
        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public string ToJson()
        {
            return JsonConvert.SerializeObject(this, Formatting.Indented);
        }

        /// <summary>
        /// Returns true if objects are equal
        /// </summary>
        /// <param name="input">Object to be compared</param>
        /// <returns>Boolean</returns>
        public override bool Equals(object input)
        {
            return this.Equals(input as QueryPayload);
        }

        /// <summary>
        /// Returns true if QueryPayload instances are equal
        /// </summary>
        /// <param name="input">Instance of QueryPayload to be compared</param>
        /// <returns>Boolean</returns>
        public bool Equals(QueryPayload input)
        {
            if (input == null)
                return false;

            return 
                (
                    this.EBIntegrationUserId == input.EBIntegrationUserId ||
                    (this.EBIntegrationUserId != null &&
                    this.EBIntegrationUserId.Equals(input.EBIntegrationUserId))
                ) && 
                (
                    this.FirstName == input.FirstName ||
                    (this.FirstName != null &&
                    this.FirstName.Equals(input.FirstName))
                ) && 
                (
                    this.LastName == input.LastName ||
                    (this.LastName != null &&
                    this.LastName.Equals(input.LastName))
                ) && 
                (
                    this.Gender == input.Gender ||
                    (this.Gender != null &&
                    this.Gender.Equals(input.Gender))
                ) && 
                (
                    this.Admission == input.Admission ||
                    this.Admission != null &&
                    this.Admission.SequenceEqual(input.Admission)
                );
        }

        /// <summary>
        /// Gets the hash code
        /// </summary>
        /// <returns>Hash code</returns>
        public override int GetHashCode()
        {
            unchecked // Overflow is fine, just wrap
            {
                int hashCode = 41;
                if (this.EBIntegrationUserId != null)
                    hashCode = hashCode * 59 + this.EBIntegrationUserId.GetHashCode();
                if (this.FirstName != null)
                    hashCode = hashCode * 59 + this.FirstName.GetHashCode();
                if (this.LastName != null)
                    hashCode = hashCode * 59 + this.LastName.GetHashCode();
                if (this.Gender != null)
                    hashCode = hashCode * 59 + this.Gender.GetHashCode();
                if (this.Admission != null)
                    hashCode = hashCode * 59 + this.Admission.GetHashCode();
                return hashCode;
            }
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        IEnumerable<System.ComponentModel.DataAnnotations.ValidationResult> IValidatableObject.Validate(ValidationContext validationContext)
        {
            yield break;
        }
    }

}
