/* 
 * Education Brands Integration Service APIs
 *
 * The integration framework is an attempt to define a standard and simple socket each brand can plug in to interact with other EB products. It defines what each product needs to do to integrate with other products. It has a set of API to interact with other products and what each product should implement to receive communication from other products. This is an API specification detailing the APIs for Education Brands IntegrationService.  Most of these APIs will be implemented in EBIS.  The APIs in the 'Product Endpoints' section has to be implemented by each of the Products.  <b>NOTE - <i>This specification is still in early development stage and is subject to change without notice.</i></b> 
 *
 * OpenAPI spec version: 1.0.0
 * Contact: sobin@schoolspeak.com
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */

using Newtonsoft.Json;
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Runtime.Serialization;
using System.Text;

namespace CB.IntegrationService.ApiModels
{
    /// <summary>
    /// QueryInformation
    /// </summary>
    [DataContract]
    public partial class QueryInformation :  IEquatable<QueryInformation>, IValidatableObject
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="QueryInformation" /> class.
        /// </summary>
        /// <param name="ApplicationId">Admission Application Id.</param>
        /// <param name="AdmissionStatus">Status of the admission.</param>
        public QueryInformation(string ApplicationId = default(string), string AdmissionStatus = default(string))
        {
            this.ApplicationId = ApplicationId;
            this.AdmissionStatus = AdmissionStatus;
        }
        
        /// <summary>
        /// Admission Application Id
        /// </summary>
        /// <value>Admission Application Id</value>
        [DataMember(Name="ApplicationId", EmitDefaultValue=false)]
        public string ApplicationId { get; set; }

        /// <summary>
        /// Status of the admission
        /// </summary>
        /// <value>Status of the admission</value>
        [DataMember(Name="AdmissionStatus", EmitDefaultValue=false)]
        public string AdmissionStatus { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            var sb = new StringBuilder();
            sb.Append("class QueryInformation {\n");
            sb.Append("  ApplicationId: ").Append(ApplicationId).Append("\n");
            sb.Append("  AdmissionStatus: ").Append(AdmissionStatus).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }
  
        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public string ToJson()
        {
            return JsonConvert.SerializeObject(this, Formatting.Indented);
        }

        /// <summary>
        /// Returns true if objects are equal
        /// </summary>
        /// <param name="input">Object to be compared</param>
        /// <returns>Boolean</returns>
        public override bool Equals(object input)
        {
            return this.Equals(input as QueryInformation);
        }

        /// <summary>
        /// Returns true if QueryInformation instances are equal
        /// </summary>
        /// <param name="input">Instance of QueryInformation to be compared</param>
        /// <returns>Boolean</returns>
        public bool Equals(QueryInformation input)
        {
            if (input == null)
                return false;

            return 
                (
                    this.ApplicationId == input.ApplicationId ||
                    (this.ApplicationId != null &&
                    this.ApplicationId.Equals(input.ApplicationId))
                ) && 
                (
                    this.AdmissionStatus == input.AdmissionStatus ||
                    (this.AdmissionStatus != null &&
                    this.AdmissionStatus.Equals(input.AdmissionStatus))
                );
        }

        /// <summary>
        /// Gets the hash code
        /// </summary>
        /// <returns>Hash code</returns>
        public override int GetHashCode()
        {
            unchecked // Overflow is fine, just wrap
            {
                int hashCode = 41;
                if (this.ApplicationId != null)
                    hashCode = hashCode * 59 + this.ApplicationId.GetHashCode();
                if (this.AdmissionStatus != null)
                    hashCode = hashCode * 59 + this.AdmissionStatus.GetHashCode();
                return hashCode;
            }
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        IEnumerable<System.ComponentModel.DataAnnotations.ValidationResult> IValidatableObject.Validate(ValidationContext validationContext)
        {
            yield break;
        }
    }

}
