/* 
 * Education Brands Integration Service APIs
 *
 * The integration framework is an attempt to define a standard and simple socket each brand can plug in to interact with other EB products. It defines what each product needs to do to integrate with other products. It has a set of API to interact with other products and what each product should implement to receive communication from other products. This is an API specification detailing the APIs for Education Brands IntegrationService.  Most of these APIs will be implemented in EBIS.  The APIs in the 'Product Endpoints' section has to be implemented by each of the Products.  <b>NOTE - <i>This specification is still in early development stage and is subject to change without notice.</i></b> 
 *
 * OpenAPI spec version: 1.0.0
 * Contact: sobin@schoolspeak.com
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */

using Newtonsoft.Json;
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Runtime.Serialization;
using System.Text;

namespace CB.IntegrationService.ApiModels
{
    /// <summary>
    /// RegisterProductResponse
    /// </summary>
    [DataContract]
    public partial class RegisterProductResponse :  IEquatable<RegisterProductResponse>, IValidatableObject
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="RegisterProductResponse" /> class.
        /// </summary>
        /// <param name="EbProductId">The Education brands product id.</param>
        public RegisterProductResponse(string EbProductId = default(string))
        {
            this.EbProductId = EbProductId;
        }
        
        /// <summary>
        /// The Education brands product id
        /// </summary>
        /// <value>The Education brands product id</value>
        [DataMember(Name="ebProductId", EmitDefaultValue=false)]
        public string EbProductId { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            var sb = new StringBuilder();
            sb.Append("class RegisterProductResponse {\n");
            sb.Append("  EbProductId: ").Append(EbProductId).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }
  
        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public string ToJson()
        {
            return JsonConvert.SerializeObject(this, Formatting.Indented);
        }

        /// <summary>
        /// Returns true if objects are equal
        /// </summary>
        /// <param name="input">Object to be compared</param>
        /// <returns>Boolean</returns>
        public override bool Equals(object input)
        {
            return this.Equals(input as RegisterProductResponse);
        }

        /// <summary>
        /// Returns true if RegisterProductResponse instances are equal
        /// </summary>
        /// <param name="input">Instance of RegisterProductResponse to be compared</param>
        /// <returns>Boolean</returns>
        public bool Equals(RegisterProductResponse input)
        {
            if (input == null)
                return false;

            return 
                (
                    this.EbProductId == input.EbProductId ||
                    (this.EbProductId != null &&
                    this.EbProductId.Equals(input.EbProductId))
                );
        }

        /// <summary>
        /// Gets the hash code
        /// </summary>
        /// <returns>Hash code</returns>
        public override int GetHashCode()
        {
            unchecked // Overflow is fine, just wrap
            {
                int hashCode = 41;
                if (this.EbProductId != null)
                    hashCode = hashCode * 59 + this.EbProductId.GetHashCode();
                return hashCode;
            }
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        IEnumerable<System.ComponentModel.DataAnnotations.ValidationResult> IValidatableObject.Validate(ValidationContext validationContext)
        {
            yield break;
        }
    }

}
