/* 
 * Education Brands Integration Service APIs
 *
 * The integration framework is an attempt to define a standard and simple socket each brand can plug in to interact with other EB products. It defines what each product needs to do to integrate with other products. It has a set of API to interact with other products and what each product should implement to receive communication from other products. This is an API specification detailing the APIs for Education Brands IntegrationService.  Most of these APIs will be implemented in EBIS.  The APIs in the 'Product Endpoints' section has to be implemented by each of the Products.  <b>NOTE - <i>This specification is still in early development stage and is subject to change without notice.</i></b> 
 *
 * OpenAPI spec version: 1.0.0
 * Contact: sobin@schoolspeak.com
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */

using Newtonsoft.Json;
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Runtime.Serialization;
using System.Text;

namespace CB.IntegrationService.ApiModels
{
    /// <summary>
    /// SubscribeEventResponse
    /// </summary>
    [DataContract]
    public partial class SubscribeEventResponse :  IEquatable<SubscribeEventResponse>, IValidatableObject
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="SubscribeEventResponse" /> class.
        /// </summary>
        /// <param name="EbEventSubscriptionId">Eb Event Subscription Id.</param>
        public SubscribeEventResponse(string EbEventSubscriptionId = default(string))
        {
            this.EbEventSubscriptionId = EbEventSubscriptionId;
        }
        
        /// <summary>
        /// Eb Event Subscription Id
        /// </summary>
        /// <value>Eb Event Subscription Id</value>
        [DataMember(Name="EbEventSubscriptionId", EmitDefaultValue=false)]
        public string EbEventSubscriptionId { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            var sb = new StringBuilder();
            sb.Append("class SubscribeEventResponse {\n");
            sb.Append("  EbEventSubscriptionId: ").Append(EbEventSubscriptionId).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }
  
        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public string ToJson()
        {
            return JsonConvert.SerializeObject(this, Formatting.Indented);
        }

        /// <summary>
        /// Returns true if objects are equal
        /// </summary>
        /// <param name="input">Object to be compared</param>
        /// <returns>Boolean</returns>
        public override bool Equals(object input)
        {
            return this.Equals(input as SubscribeEventResponse);
        }

        /// <summary>
        /// Returns true if SubscribeEventResponse instances are equal
        /// </summary>
        /// <param name="input">Instance of SubscribeEventResponse to be compared</param>
        /// <returns>Boolean</returns>
        public bool Equals(SubscribeEventResponse input)
        {
            if (input == null)
                return false;

            return 
                (
                    this.EbEventSubscriptionId == input.EbEventSubscriptionId ||
                    (this.EbEventSubscriptionId != null &&
                    this.EbEventSubscriptionId.Equals(input.EbEventSubscriptionId))
                );
        }

        /// <summary>
        /// Gets the hash code
        /// </summary>
        /// <returns>Hash code</returns>
        public override int GetHashCode()
        {
            unchecked // Overflow is fine, just wrap
            {
                int hashCode = 41;
                if (this.EbEventSubscriptionId != null)
                    hashCode = hashCode * 59 + this.EbEventSubscriptionId.GetHashCode();
                return hashCode;
            }
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        IEnumerable<System.ComponentModel.DataAnnotations.ValidationResult> IValidatableObject.Validate(ValidationContext validationContext)
        {
            yield break;
        }
    }

}
